{
 "title": "ML Monitoring",
 "time": { "from": "2024-01-29T07:59:10.621Z", "to": "2024-02-25T07:59:14.470Z" },
 "panels": [
  {
   "title": "Model Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT metric_value AS \"current\", created_at FROM model_metrics WHERE metric_name = 'current_rmse' "
    },
    {
     "rawSql": "SELECT metric_value AS \"reference\", created_at FROM model_metrics WHERE metric_name = 'reference_rmse'\n"
    }
   ]
  },
  {
   "title": "Target Drift",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT metric_value, created_at FROM model_metrics WHERE metric_name = 'target_drift_score' ORDER BY created_at DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Model performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT metric_value AS \"current\", created_at FROM model_metrics WHERE metric_name = 'current_rmse' LIMIT 50 "
    },
    {
     "rawSql": "SELECT metric_value AS \"reference\", created_at FROM model_metrics WHERE metric_name = 'reference_rmse' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Mean Bedrooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT metric_value AS \"current\", created_at FROM model_metrics WHERE metric_name = 'bedrooms_current_mean' LIMIT 50 "
    },
    {
     "rawSql": "SELECT metric_value AS \"reference\", created_at FROM model_metrics WHERE metric_name = 'bedrooms_reference_mean' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Data Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT metric_value, created_at FROM model_metrics WHERE metric_name = 'share_of_drifted_columns' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Walk Score Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT metric_value AS \"current\", created_at FROM model_metrics WHERE metric_name = 'walk_score_current_mean' LIMIT 50 "
    },
    {
     "rawSql": "SELECT metric_value AS \"reference\", created_at FROM model_metrics WHERE metric_name = 'walk_score_reference_mean' LIMIT 50 "
    }
   ]
  }
 ]
}