{
 "title": "Rightmove Scraper",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (SUM(item_scraped_count)::FLOAT / (SUM(item_scraped_count) + SUM(log_count_error))) * 100 AS success_percentage\nFROM\n  scrapy_rightmove_rental_stats;\n"
    }
   ]
  },
  {
   "title": "Properties added to date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(item_scraped_count) FROM scrapy_rightmove_rental_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Properties added",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT created_at, item_scraped_count FROM scrapy_rightmove_rental_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT log_count_error, created_at FROM scrapy_rightmove_rental_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT mem_usage_max, created_at FROM scrapy_rightmove_rental_stats LIMIT 50 "
    }
   ]
  }
 ]
}