apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapy
  template:
    metadata:
      labels:
        app: scrapy
    spec:
      containers:
      - name: scrapy
        image: <your-scrapy-docker-image>
        ports:
        - containerPort: 6800
        env:
        - name: MONGO_URL
          value: "mongodb://<mongodb-service-name>:27017/"

---

apiVersion: v1
kind: Service
metadata:
  name: scrapy-service
spec:
  type: NodePort
  selector:
    app: scrapy
  ports:
    - protocol: TCP
      port: 6800
      targetPort: 6800