# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    url: realestate-database.czkkjkojmucd.eu-west-2.rds.amazonaws.com:5432
    database: monitoring
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      sslmode: 'require'